# Chemical Kinetics

In [16]:
import cantera as ct
import numpy as np

In [2]:
g = ct.Solution('gri30.cti')
r = g.reaction(2) # reaction object
r

<ElementaryReaction: H2 + O <=> H + OH>

In [3]:
r.reactants

{'H2': 1.0, 'O': 1.0}

In [4]:
r.products

{'H': 1.0, 'OH': 1.0}

In [5]:
r.rate

Arrhenius(A=38.7, b=2.7, E=2.61918e+07)

In [6]:
#  find the indices of just those reactions which convert CO into CO2:
II = [i for i, r in enumerate(g.reactions())
     if 'CO' in r.reactants and 'CO2' in r.products]

for i in II:
    print(g.reaction(i).equation)

CO + O (+M) <=> CO2 (+M)
CO + O2 <=> CO2 + O
CO + OH <=> CO2 + H
CO + HO2 <=> CO2 + OH


In [7]:
#  set the composition to an interesting equilibrium state:
g.TPX = 300, 101325, {'CH4':0.6, 'O2':1.0, 'N2':3.76}
g.equilibrate('HP')

In [8]:
# net reaction rates are essentially zero
g.net_rates_of_progress[II]

array([3.38813179e-19, 1.16467030e-20, 3.77475828e-15, 1.86347248e-19])

In [10]:
# check major gas composition
g['CH4','O2','CO2','H2O','N2'].X

array([1.00226619e-13, 2.82794886e-05, 6.26372504e-02, 1.88237224e-01,
       6.75728263e-01])

In [11]:
# decrease the temperature of the mixture:
g.TP = g.T-100, None
g.net_rates_of_progress[II]

array([3.18644948e-05, 5.00489577e-08, 1.05964923e-01, 2.89502609e-06])

In [12]:
# check major gas composition after temperature decrease
g['CH4','O2','CO2','H2O','N2'].X

array([1.00226619e-13, 2.82794886e-05, 6.26372504e-02, 1.88237224e-01,
       6.75728263e-01])

In [14]:
# enthalpy change associated with each of these reactions:
g.delta_enthalpy[II]

array([-5.33034657e+08, -2.23248515e+07, -8.76650086e+07, -2.49169628e+08])

In [17]:
# total heat release rate
np.dot(g.net_rates_of_progress, g.delta_enthalpy)

-58013370.720875815

In [18]:
# heat rate from the species production rates:
np.dot(g.net_production_rates, g.partial_molar_enthalpies)

-58013370.7208757

In [19]:
# contribution from just the selected reactions is:
np.dot(g.net_rates_of_progress[II], g.delta_enthalpy[II])

-9307123.262565006

In [ ]:
# https://cantera.org/tutorials/python-tutorial.html